
// app/layout.tsx
import { Providers } from "./Provider";

export const metadata = {
  title: 'SMART-STATE-GROUP',
  description: 'Generated by create next app',
}

// app/layout.tsx
//import { Providers } from "./providers";

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {children}
    
        </Providers>
      </body>
    </html>
  );
}

//'use client'

//import './globals.css'
// import { Inter } from 'next/font/google'
// import { ChakraProvider } from '@chakra-ui/react'
//import { CacheProvider } from '@chakra-ui/next-js'
//import { ChakraProvider } from '@chakra-ui/react'

//const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'SMART-STATE-GROUP',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>
//     <ChakraProvider>  
//     {children}
//     </ChakraProvider>
    
      
//       </body>
//     </html>
//   )
// }
